### ISSUE TITLE
USER STORY: View page

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp4-project#1]
USER STORY:
As a **Site Visitor** I can **visit the page** so that **I can view it's contents**

**Acceptance criteria**
1. Allow users to view the main page

**Tasks**
- [x] create generic listview in views.py
- [x] create html template to render view
- [x] connect template via urls.py

Story points: 5
