### ISSUE TITLE
USER STORY: User Preferences

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp4-project#11]
USER STORY:
As a **Site Visitor** I can **change the visuals of the page** so that **I can personalize my experience**

**Acceptance criteria**
1. user can open a 'preference' window from navbar dropdown menu
2. the user can switch between normal- and dark-theme

**Tasks**
- [ ] create a model for user preferences
- [ ] add user preferences to User model
- [ ] set up a settings page template
- [ ] connect it via urls.py
- [ ] pass the user preferences through a context processor
- [ ] create a dark theme CSS
- [ ] import the new CSS to template if defined in user preferences
