### ISSUE TITLE
USER STORY: Admin Menu Search

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp4-project#12]
USER STORY:
As a **Site Admin** I can **search through posts and comments** so that **I can moderate the site**

**Acceptance criteria**
1. thoughts and comment can be searched for by title, content and author in the admin menu

**Tasks**
- [x] create admin.py
- [x] create a class for each model prefixed with @admin.register(MODEL)
- [x] define what fields can be searched for in each class

Story points: 1
