### ISSUE TITLE
USER STORY: Sign up

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp4-project#13]
USER STORY:
As a **Site Visitor** I can **sign up** so that **I have an account to interact with the website through**

**Acceptance criteria**
1. users can sign up for an account
3. users have access to the sign-up page from the navbar / log-in page

**Tasks**
- [x] install allauth
- [x] create page for sign-up
- [x] add allauth form to sign-up page
- [x] connect page via urls.py
- [x] add link to login from base.html and the log-in page

Story points: 3
