### ISSUE TITLE
USER STORY: Log Out

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp4-project#14]
USER STORY:
As a **Logged in Site Visitor** I can **log out of my account** so that **I can avoid someone else accessing my account**

**Acceptance criteria**
1. users can log out
2. users have access to the logout button from the navbar

**Tasks**
- [x] create confirmation page for signing out
- [x] connect page via urls.py
- [x] add link to navbar in base.html

Story points: 1
