### ISSUE TITLE
USER STORY: Delete Thoughts

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp4-project#15]
USER STORY:
As a **Site Visitor** I can **delete my posts** so that **I can remove things I no longer want to share**

**Acceptance criteria**
1. a delete button is visible on the user's posts
2. user can delete their own posts

**Tasks**
- [x] add a delete button to each post template
- [x] create a view that deletes posts based on post id
- [x] connect the view through urls.py 

Story points: 2
