### ISSUE TITLE
USER STORY: Liking Comments

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp4-project#16]
USER STORY:
As a **Site Visitor** I can **like comments** so that **I can show which comments I enjoyed**

**Acceptance criteria**
1. a 'like' button is visible on each comment
2. users can click the button to be added to the 'likes' of a post

**Tasks**
- [x] add 'likes' to the comment model
- [x] create a view that adds the user to the list of likes
- [x] display the likes on comment in the page template

Story points: 2
