### ISSUE TITLE
USER STORY: Password Reset

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp4-project#17]
USER STORY:
As a **Site Visitor** I can **reset my password** so that **I can regain my account if I forget my username/password**

**Acceptance criteria**
1. users can enter their e-mail address to be sent a recovery e-mail
2. users receive a link to reset their password

**Tasks**
- [ ] create a 'forgot your password' page
- [ ] add a form for users to fill out their e-mail
- [ ] use allauth.account.views.PasswordResetView to reset the password
- [ ] connect the page through urls.py
