### ISSUE TITLE
USER STORY: Edit Thoughts

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp4-project#18]
USER STORY:
As a **Site Visitor** I can **edit my posts** so that **I can correct any mistakes**

**Acceptance criteria**
1. an edit button is visible on the user's posts
2. user can edit their own posts

**Tasks**
- [x] add an edit button to each post template
- [x] create an 'edit thought' page with the thought form in it
- [x] create a view that fills in the form based on thought content
- [x] update the thought object using the new form
- [x] connect the view through urls.py 

Story points: 3
