### ISSUE TITLE
USER STORY: Searching by Tags

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp4-project#19]
USER STORY:
As a **Site Visitor** I can **search by tags** so that **I can quickly find content similar to what I'm currently reading**

**Acceptance criteria**
1. users can search for content using tags
2. users can click on tags to start a search

**Tasks**
- [x] add tags + tag selection widget into search form
- [x] change search filter to include tags
- [x] add links to start a search on each tag produced in the template

Story points: 2
