### ISSUE TITLE
USER STORY: Log In

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp4-project#2]
USER STORY:
As a **Site Visitor** I can **log in** so that **interact with the website**

**Acceptance criteria**
1. users can log in
2. users have access to the page from the navbar

**Tasks**
- [x] create page for sign-in
- [x] add allauth form to sign-in page
- [x] connect page via urls.py
- [x] add link to login from base.html

Story points: 2
