### ISSUE TITLE
USER STORY: Post Thoughts

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp4-project#3]
USER STORY:
As a **Site Visitor** I can **make posts** so that **I can share my thoughts**

**Acceptance criteria**
1. users can make posts
2. posts can be stored

**Tasks**
- [x] install crispyforms
- [x] create a thought model
- [x] create a thought form 
- [x] create a view to build a thought object using the form
- [x] create a page featuring the form

Story points: 3
