### ISSUE TITLE
USER STORY: View posts

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp4-project#4]
USER STORY:
As a **Site Visitor** I can **view posts** so that **read what has been posted**

**Acceptance criteria**
1. user can view title, content and author of the post
2. several posts can be viewed from the same page

**Tasks**
- [x] create a view that returns a queryset of all thoughts 
- [x] build a page template that displays the thoughts from the queryset
- [x] connect the page via urls.py

Story points: 5
