### ISSUE TITLE
USER STORY: Liking Posts

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp4-project#5]
USER STORY:
As a **Site Visitor** I can **like posts** so that **I can show which posts I enjoy**

**Acceptance criteria**
1. a 'like' button and counter is visible on each posted thought
3. users can click the button to be added to the 'likes' of a post

**Tasks**
- [x] add 'likes' to the thought model
- [x] create a view that adds the user to the list of likes
- [x] display the likes on the page template

Story points: 2
