### ISSUE TITLE
USER STORY: Searching

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp4-project#6]
USER STORY:
As a **Site Visitor** I can **search for content** so that **I can find what I'm looking for**

**Acceptance criteria**
1. user can search by title, content or author
2. search results are displayed on the search page in order

**Tasks**
- [x] create a search filter in filters.py
- [x] create a page featuring a search form
- [x] create a function in views that filters posts using the search filter
- [x] display search results on template page

Story points: 3
