### ISSUE TITLE
USER STORY: Adding Tags

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp4-project#7]
USER STORY:
As a **Site Visitor** I can **tag my posts** so that **I can categorize my content**

**Acceptance criteria**
1. tags can be created/altered by a superuser
2. tags can be applied to posts during creation

**Tasks**
- [x] create tag model
- [x] add tags to thought model
- [x] create tag selection widget in widgets.py
- [x] add tag selection widget into thought creation form
- [x] display tags underneat their respective posts

Story points: 5
