### ISSUE TITLE
USER STORY: View User Profiles

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp4-project#8]
USER STORY:
As a **Site Visitor** I can **view other users' profiles** so that **learn more about the poster**

**Acceptance criteria**
1. users can view information about an author on a separate page
2. the page can be reached by clicking on a post author

**Tasks**
- [x] create a view that fetches user information by user id
- [x] create a page template that displays the information
- [x] connect the page via urls.py
- [x] add link to page on every post authors name

Story points: 3
