### ISSUE TITLE
USER STORY: Post Comments

### ISSUE THREAD

**Issue by AndreeeasN** [AndreeeasN/pp4-project#9]
USER STORY:
As a **Site Visitor** I can **leave comments on posts** so that **I can share my opinion**

**Acceptance criteria**
1. user can view posts on a separate page
2. user can leave comments on this page
3. user can read other people's comments

**Tasks**
- [x] create new comment model
- [x] add 'comments' to thought model
- [x] create a commenting form
- [x] create view that fetches thought information 
- [x] create new page template that displays thought information and comment form
- [x] create view that builds comment using the form and attaches it to specified thought

Story points: 5
